"""MOSDAC Central Product Registry and Metadata Definitions.

Defines product configurations, categories, units, spatial resolutions,
parsing targets, and environment toggle bindings for all supported MOSDAC products.
"""

from typing import Dict, Any, Optional
from enum import Enum


class ProductCategory(str, Enum):
    WEATHER = "weather"
    ENVIRONMENT = "environment"
    OCEAN = "ocean"


class ProductStatus(str, Enum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"
    DISABLED = "disabled"
    ERROR = "error"


MOSDAC_PRODUCTS: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # GROUP A: WEATHER PRODUCTS
    # =========================================================================
    "3SIMG_L2B_HEM": {
        "product_id": "3SIMG_L2B_HEM",
        "name": "Hydro-Estimator Rainfall Rate",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Precipitation rate estimated using infrared cloud-top brightness temperature regression (Hydro-Estimator Method).",
        "dataset_name": "HEM",
        "unit": "mm/hr",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Indian Landmass & Surrounding Oceans (0.84°E to 163.15°E, -81.04°S to 81.04°N)",
        "hdf5_dataset_path": "/HEM",
        "hdf5_lat_path": "/Latitude",
        "hdf5_lon_path": "/Longitude",
        "lat_scale": 0.01,
        "lon_scale": 0.01,
        "fill_value": -999.0,
        "valid_min": 0.0,
        "valid_max": 250.0,
        "env_flag": "MOSDAC_RAINFALL_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/rainfall/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2G_IMR": {
        "product_id": "3SIMG_L2G_IMR",
        "name": "INSAT Multispectral Rainfall",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2G",
        "description": "Rainfall estimated from multiple optical and infrared channels of INSAT-3DS Imager.",
        "dataset_name": "IMR",
        "unit": "mm/hr",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "South Asia / Indian Ocean Region",
        "hdf5_dataset_path": "/IMR",
        "hdf5_lat_path": "/latitude",
        "hdf5_lon_path": "/longitude",
        "lat_scale": 1.0,
        "lon_scale": 1.0,
        "fill_value": -999.0,
        "valid_min": 0.0,
        "valid_max": 250.0,
        "env_flag": "MOSDAC_RAINFALL_IMR_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/rainfall-imr/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2B_CTP": {
        "product_id": "3SIMG_L2B_CTP",
        "name": "Cloud Top Properties (Pressure & Temperature)",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Cloud top pressure (CTP) and cloud top temperature (CTT) derived from thermal and water vapour channels.",
        "dataset_name": "CTP",
        "unit": "hPa",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Indian Subcontinent & Oceanic Sectors",
        "hdf5_dataset_path": "/CTP",
        "hdf5_lat_path": "/Latitude",
        "hdf5_lon_path": "/Longitude",
        "lat_scale": 0.01,
        "lon_scale": 0.01,
        "fill_value": -999.0,
        "valid_min": 50.0,
        "valid_max": 1050.0,
        "env_flag": "MOSDAC_CLOUD_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/cloud/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2B_UTH": {
        "product_id": "3SIMG_L2B_UTH",
        "name": "Upper Tropospheric Humidity",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Relative humidity in the upper troposphere (500-200 hPa) derived from 6.7 µm water vapour radiance.",
        "dataset_name": "UTH",
        "unit": "%",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Full Disk Indian Region",
        "hdf5_dataset_path": "/UTH",
        "hdf5_lat_path": "/Latitude",
        "hdf5_lon_path": "/Longitude",
        "lat_scale": 0.01,
        "lon_scale": 0.01,
        "fill_value": -999.0,
        "valid_min": 0.0,
        "valid_max": 100.0,
        "env_flag": "MOSDAC_HUMIDITY_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/humidity/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2B_OLR": {
        "product_id": "3SIMG_L2B_OLR",
        "name": "Outgoing Longwave Radiation",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Total outgoing longwave radiation flux thermally emitted from the earth-atmosphere system.",
        "dataset_name": "OLR",
        "unit": "W/m²",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Full Disk Indian Region",
        "hdf5_dataset_path": "/OLR",
        "hdf5_lat_path": "/Latitude",
        "hdf5_lon_path": "/Longitude",
        "lat_scale": 0.01,
        "lon_scale": 0.01,
        "fill_value": -999.0,
        "valid_min": 50.0,
        "valid_max": 400.0,
        "env_flag": "MOSDAC_OLR_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/olr/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2C_FOG": {
        "product_id": "3SIMG_L2C_FOG",
        "name": "Night & Day Fog Detection",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2C",
        "description": "Multi-spectral threshold detection of radiation and advection fog using mid-IR and thermal channels.",
        "dataset_name": "FOG",
        "unit": "Mask (0: Clear, 1: Fog)",
        "spatial_resolution": "1 km / 4 km projected",
        "temporal_frequency": "Every 30 to 60 minutes",
        "coverage": "Indo-Gangetic Plain & Indian Landmass",
        "hdf5_dataset_path": "/FOG",
        "hdf5_intensity_path": "/FOG_INTENSITY",
        "hdf5_lat_path": "/Y",
        "hdf5_lon_path": "/X",
        "lat_scale": 1.0,
        "lon_scale": 1.0,
        "fill_value": -128,
        "valid_min": 0.0,
        "valid_max": 5.0,
        "env_flag": "MOSDAC_FOG_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/fog/index.html",
        "render_type": "categorical_mask",
    },
    "3SIMG_L2B_CMV": {
        "product_id": "3SIMG_L2B_CMV",
        "name": "Cloud Motion Vector (Atmospheric Wind)",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Atmospheric motion vectors (wind speed & direction) derived from tracking cloud features.",
        "dataset_name": "CMV",
        "unit": "m/s",
        "spatial_resolution": "Variable vector grid",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Indian Subcontinent & Oceanic Sectors",
        "env_flag": "MOSDAC_CLOUD_MOTION_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Product ID not active in MOSDAC OpenSearch catalog feed (HTTP 500 Data Unavailable).",
        "test_map_path": "/test/cloud-motion/index.html",
        "render_type": "vector_field",
    },
    "3SIMG_L2B_WVW": {
        "product_id": "3SIMG_L2B_WVW",
        "name": "Water Vapour Wind Vectors",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Wind vectors derived from tracking moisture gradients in water vapour absorption bands.",
        "dataset_name": "WVW",
        "unit": "m/s",
        "spatial_resolution": "Variable vector grid",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Middle & Upper Troposphere",
        "env_flag": "MOSDAC_WATER_VAPOUR_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Data feed not currently published in operational OpenSearch catalog.",
        "test_map_path": "/test/water-vapour/index.html",
        "render_type": "vector_field",
    },
    "3SSND_L2B_ATD": {
        "product_id": "3SSND_L2B_ATD",
        "name": "Atmospheric Sounder Temperature & Humidity Profile",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "SOUNDER",
        "level": "L2B",
        "description": "Vertical atmospheric soundings of temperature (K) and moisture across 40 pressure levels (1000 to 10 hPa).",
        "dataset_name": "ATD",
        "unit": "K / %",
        "spatial_resolution": "10 km sounder footprints",
        "temporal_frequency": "Hourly",
        "coverage": "Indian Landmass",
        "env_flag": "MOSDAC_TEMPERATURE_PROFILE_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "INSAT-3DS Sounder operational L2B stream not published via current OpenSearch endpoint.",
        "test_map_path": "/test/atmospheric-profile/index.html",
        "render_type": "vertical_profile",
    },
    "3SSND_L2B_TPW": {
        "product_id": "3SSND_L2B_TPW",
        "name": "Total Precipitable Water",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "SOUNDER",
        "level": "L2B",
        "description": "Vertically integrated atmospheric water vapor column.",
        "dataset_name": "TPW",
        "unit": "mm",
        "spatial_resolution": "10 km",
        "temporal_frequency": "Hourly",
        "coverage": "Indian Subcontinent",
        "env_flag": "MOSDAC_PRECIPITABLE_WATER_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Sounder TPW feed unavailable under current catalog credentials.",
        "test_map_path": "/test/precipitable-water/index.html",
        "render_type": "fluid_raster",
    },
    "3SSND_L2B_DMI": {
        "product_id": "3SSND_L2B_DMI",
        "name": "Atmospheric Stability & Lifted Index",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "SOUNDER",
        "level": "L2B",
        "description": "Severe weather indices (Dry Microburst Index, Lifted Index, Total Totals, K-Index) for convective storm forecasting.",
        "dataset_name": "DMI",
        "unit": "Index / °C",
        "spatial_resolution": "10 km",
        "temporal_frequency": "Hourly",
        "coverage": "Indian Landmass",
        "env_flag": "MOSDAC_STABILITY_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Atmospheric stability stream not published in catalog feed.",
        "test_map_path": "/test/stability/index.html",
        "render_type": "fluid_raster",
    },
    "3SSND_L2B_OZN": {
        "product_id": "3SSND_L2B_OZN",
        "name": "Total Column Ozone",
        "category": ProductCategory.WEATHER,
        "satellite": "INSAT-3DS",
        "sensor": "SOUNDER",
        "level": "L2B",
        "description": "Total column atmospheric ozone retrieved from 9.6 µm infrared channel.",
        "dataset_name": "OZN",
        "unit": "Dobson Units (DU)",
        "spatial_resolution": "10 km",
        "temporal_frequency": "Daily / Hourly",
        "coverage": "Indian Region",
        "env_flag": "MOSDAC_OZONE_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Ozone product unavailable under current MOSDAC access.",
        "test_map_path": "/test/ozone/index.html",
        "render_type": "fluid_raster",
    },

    # =========================================================================
    # GROUP B: ENVIRONMENT PRODUCTS
    # =========================================================================
    "3SIMG_L2C_SNW": {
        "product_id": "3SIMG_L2C_SNW",
        "name": "Snow Cover & Fractional Snow Cover",
        "category": ProductCategory.ENVIRONMENT,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2C",
        "description": "Fractional snow cover and binary snow/ice mask over Himalayan catchments derived from visible and SWIR bands.",
        "dataset_name": "SNW",
        "unit": "%",
        "spatial_resolution": "1 km projected",
        "temporal_frequency": "Daily",
        "coverage": "Himalayan Region & Northern India (20°N - 38°N, 68°E - 98°E)",
        "hdf5_dataset_path": "/FSC",
        "hdf5_mask_path": "/SNW",
        "hdf5_lat_path": "/Y",
        "hdf5_lon_path": "/X",
        "lat_scale": 1.0,
        "lon_scale": 1.0,
        "fill_value": -999.0,
        "valid_min": 0.0,
        "valid_max": 100.0,
        "env_flag": "MOSDAC_SNOW_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/snow/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2G_AOD": {
        "product_id": "3SIMG_L2G_AOD",
        "name": "Aerosol Optical Depth (650 nm)",
        "category": ProductCategory.ENVIRONMENT,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2G",
        "description": "Aerosol optical thickness at 650 nm providing particulate matter and air quality indicators over land and ocean.",
        "dataset_name": "AOD",
        "unit": "Optical Thickness (Unitless)",
        "spatial_resolution": "0.05° (~5 km regular grid)",
        "temporal_frequency": "Daytime 30-min",
        "coverage": "Indian Subcontinent & Northern Indian Ocean",
        "hdf5_dataset_path": "/AOD",
        "hdf5_lat_path": "/latitude",
        "hdf5_lon_path": "/longitude",
        "lat_scale": 1.0,
        "lon_scale": 1.0,
        "fill_value": -999.0,
        "valid_min": 0.01,
        "valid_max": 3.0,
        "env_flag": "MOSDAC_AEROSOL_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/aerosol/index.html",
        "render_type": "fluid_raster",
    },
    "3SIMG_L2C_FIR": {
        "product_id": "3SIMG_L2C_FIR",
        "name": "Active Fire & Thermal Anomalies",
        "category": ProductCategory.ENVIRONMENT,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2C",
        "description": "High-temperature sub-pixel biomass burning and agricultural stubble fire detections.",
        "dataset_name": "FIR",
        "unit": "MW (Fire Radiative Power) / Hotspots",
        "spatial_resolution": "1 km / 4 km",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Indian Landmass",
        "env_flag": "MOSDAC_FIRE_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Fire product not currently distributed in operational OpenSearch catalog feed.",
        "test_map_path": "/test/fire/index.html",
        "render_type": "point_clusters",
    },
    "3SIMG_L2C_SMK": {
        "product_id": "3SIMG_L2C_SMK",
        "name": "Smoke & Haze Plume Boundary",
        "category": ProductCategory.ENVIRONMENT,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2C",
        "description": "Delineation of agricultural and wildfire smoke plumes using visible reflectance ratioing.",
        "dataset_name": "SMK",
        "unit": "Index / Binary Plume Area",
        "spatial_resolution": "1 km",
        "temporal_frequency": "Daytime",
        "coverage": "Indo-Gangetic Plain",
        "env_flag": "MOSDAC_SMOKE_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Dedicated smoke mask unavailable via current MOSDAC access endpoint.",
        "test_map_path": "/test/smoke/index.html",
        "render_type": "polygon_overlay",
    },

    # =========================================================================
    # GROUP C: OCEAN & MARINE PRODUCTS
    # =========================================================================
    "3SIMG_L2B_SST": {
        "product_id": "3SIMG_L2B_SST",
        "name": "Sea Surface Temperature",
        "category": ProductCategory.OCEAN,
        "satellite": "INSAT-3DS",
        "sensor": "IMAGER",
        "level": "L2B",
        "description": "Sub-skin sea surface temperature retrieved from split-window thermal channels over cloud-free ocean pixels.",
        "dataset_name": "SST",
        "unit": "°C",
        "spatial_resolution": "0.04° (~4 km)",
        "temporal_frequency": "Every 30 minutes",
        "coverage": "Arabian Sea, Bay of Bengal, and Equatorial Indian Ocean",
        "hdf5_dataset_path": "/SST_REG",
        "hdf5_lat_path": "/Latitude",
        "hdf5_lon_path": "/Longitude",
        "lat_scale": 0.01,
        "lon_scale": 0.01,
        "fill_value": -999.0,
        "valid_min": -3.0,  # in Celsius
        "valid_max": 45.0,  # in Celsius
        "kelvin_offset": 273.15,
        "env_flag": "MOSDAC_SST_ENABLED",
        "operational_status": ProductStatus.AVAILABLE,
        "test_map_path": "/test/sst/index.html",
        "render_type": "fluid_raster",
    },
    "O3SCA_L2B_WND": {
        "product_id": "O3SCA_L2B_WND",
        "name": "Oceansat-3 / SCATSAT-1 Ocean Surface Wind Vectors",
        "category": ProductCategory.OCEAN,
        "satellite": "Oceansat-3 / SCATSAT-1",
        "sensor": "Scatterometer (OSCAT)",
        "level": "L2B",
        "description": "10-meter neutral equivalent ocean surface vector wind speed and direction derived from Ku-band backscatter.",
        "dataset_name": "SCAT_WND",
        "unit": "m/s & Degrees",
        "spatial_resolution": "12.5 km / 25 km wind vector cells",
        "temporal_frequency": "Daily orbital swaths",
        "coverage": "Global Oceans & Indian EEZ",
        "env_flag": "MOSDAC_SCATSAT_WIND_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "Oceansat-3 OSCAT stream not accessible under current MOSDAC credentials.",
        "test_map_path": "/test/scatsat-wind/index.html",
        "render_type": "vector_arrows",
    },
    "O3OCM_L2B_CHL": {
        "product_id": "O3OCM_L2B_CHL",
        "name": "Ocean Colour & Chlorophyll Concentration",
        "category": ProductCategory.OCEAN,
        "satellite": "Oceansat-3",
        "sensor": "Ocean Colour Monitor (OCM-3)",
        "level": "L2B",
        "description": "Near-surface Chlorophyll-a concentration and total suspended matter (TSM) for marine fishery and productivity analytics.",
        "dataset_name": "CHL",
        "unit": "mg/m³",
        "spatial_resolution": "360 m local / 1 km global",
        "temporal_frequency": "Every 2 days orbital revisit",
        "coverage": "Arabian Sea & Bay of Bengal",
        "env_flag": "MOSDAC_CHLOROPHYLL_ENABLED",
        "operational_status": ProductStatus.UNAVAILABLE,
        "unavailability_reason": "OCM-3 Chlorophyll stream requires specialized institutional authorization.",
        "test_map_path": "/test/ocean-colour/index.html",
        "render_type": "fluid_raster",
    },
}


def get_product_definition(product_id: str) -> Optional[Dict[str, Any]]:
    """Retrieve product metadata definition from central registry."""
    return MOSDAC_PRODUCTS.get(product_id)


def get_products_by_category(category: ProductCategory) -> Dict[str, Dict[str, Any]]:
    """Filter products by domain category (weather, environment, ocean)."""
    return {k: v for k, v in MOSDAC_PRODUCTS.items() if v["category"] == category}


def get_available_products() -> Dict[str, Dict[str, Any]]:
    """Retrieve products verified to be live and accessible from MOSDAC."""
    return {k: v for k, v in MOSDAC_PRODUCTS.items() if v["operational_status"] == ProductStatus.AVAILABLE}
