import { useState, useEffect } from 'react';
import { X, HelpCircle, Mail, MessageSquare, ShieldCheck, FileText, Eye, CheckCircle2, Send } from 'lucide-react';

const MODAL_CONTENT = {
  faqs: {
    title: 'Frequently Asked Questions',
    subtitle: 'Common questions about the TATVA Weather Big Data Analytics Platform',
    icon: HelpCircle,
    sections: [
      {
        q: 'What data sources power TATVA?',
        a: 'TATVA ingests high-frequency real-time payloads from ISRO MOSDAC (INSAT-3D/3DR/3DS, Oceansat-3), IMD Doppler Weather Radars (DWR), AWS networks, and GFS/WRF numerical weather models via an Apache Kafka streaming lakehouse.'
      },
      {
        q: 'How often is weather and radar data updated?',
        a: 'Satellite and radar payloads stream continuously with automated 5-minute ingestion intervals. Gridded analysis maps refresh every 15 minutes, and disaster alerts trigger sub-second upon threshold breach.'
      },
      {
        q: 'How are multi-criteria disaster alerts determined?',
        a: 'Alerts combine Doppler reflectivity (>45 dBZ for cloudbursts), multi-hour accumulated rainfall (IMD extreme thresholds), hydrological soil saturation indices, and historical vulnerability weights.'
      },
      {
        q: 'Who receives the incident reports submitted on this platform?',
        a: 'Submitted reports are geo-tagged and instantly queued to State Disaster Management Authorities (SDMA), District Emergency Operations Centers (DEOC), and NDMA response coordinators.'
      }
    ]
  },
  contact: {
    title: 'Contact TATVA Operations',
    subtitle: 'National Weather Big Data & Disaster Early Warning Coordination',
    icon: Mail,
    details: [
      { label: 'National Operations Center', value: 'TATVA Core Ops, Mausam Bhawan Complex, Lodhi Road, New Delhi 110003' },
      { label: 'Emergency SDMA Hotline', value: '1070 (Toll-Free National) / 1077 (District Collectorates)' },
      { label: 'Technical Operations Desk', value: 'support@tatva-weather.gov.in / ops@tatva.in' },
      { label: 'Operational Availability', value: '24x7x365 Continuous Real-Time Monitoring Desk' }
    ]
  },
  feedback: {
    title: 'Submit Platform Feedback',
    subtitle: 'Help improve TATVA predictive analytics and disaster response tooling',
    icon: MessageSquare,
    isForm: true
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'Compliance with India Digital Personal Data Protection (DPDP) Act 2023',
    icon: ShieldCheck,
    text: [
      'TATVA is committed to protecting citizen privacy. Location data gathered during citizen incident reporting is solely used for disaster triangulation, emergency verification, and SDMA dispatch.',
      'We do not commercialize or transfer personal identifying information. Telemetry gathered from browser sessions is strictly anonymized performance metrics used for latency optimization.',
      'All automated radar and satellite metadata is public domain data distributed in adherence with National Data Sharing and Accessibility Policy (NDSAP).'
    ]
  },
  terms: {
    title: 'Terms of Use',
    subtitle: 'Guidelines for utilizing TATVA meteorological big data and APIs',
    icon: FileText,
    text: [
      'TATVA analytical products, radar layers, and flood risk zones are published in real-time for public safety, disaster preparedness, and scientific research.',
      'Emergency alerts and advisories generated by TATVA complement statutory notifications from IMD and SDMA. District administrations should verify ground telemetry prior to triggering regional evacuation protocols.',
      'Automated batch scraping of raw Kafka streams without API registration is prohibited to guarantee zero-latency QoS for frontline first responders.'
    ]
  },
  accessibility: {
    title: 'Accessibility Statement',
    subtitle: 'Committed to universal digital access across India',
    icon: Eye,
    text: [
      'TATVA adheres to World Wide Web Consortium (W3C) Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards.',
      'Key architectural enhancements include full keyboard navigation across maps and regional data tables, high-contrast radar visualization palettes, and semantic ARIA labeling for assistive screen readers.',
      'We continuously optimize the platform for low-bandwidth 2G/3G mobile devices across rural district emergency operational centers.'
    ]
  }
};

export function FooterInfoModal({ type, onClose }) {
  const [feedbackCategory, setFeedbackCategory] = useState('data_accuracy');
  const [feedbackEmail, setFeedbackEmail] = useState('');
  const [feedbackMessage, setFeedbackMessage] = useState('');
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  if (!type || !MODAL_CONTENT[type]) return null;

  const content = MODAL_CONTENT[type];
  const IconComponent = content.icon;

  const handleFeedbackSubmit = (e) => {
    e.preventDefault();
    setFeedbackSubmitted(true);
    setTimeout(() => {
      setFeedbackSubmitted(false);
      setFeedbackEmail('');
      setFeedbackMessage('');
      onClose();
    }, 2000);
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="footer-info-modal-title"
      className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl max-w-xl w-full p-6 shadow-2xl border border-slate-200 relative animate-in zoom-in-95 max-h-[85vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          aria-label="Close modal"
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 pb-4 border-b border-slate-100">
          <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
            <IconComponent className="w-5 h-5" />
          </div>
          <div>
            <h3 id="footer-info-modal-title" className="text-lg font-bold text-slate-900">
              {content.title}
            </h3>
            <p className="text-xs text-slate-500">{content.subtitle}</p>
          </div>
        </div>

        {/* Body Content */}
        <div className="flex-1 overflow-y-auto py-4 space-y-4 text-xs leading-relaxed text-slate-600">
          {type === 'faqs' && (
            <div className="space-y-4">
              {content.sections.map((sec, idx) => (
                <div key={idx} className="bg-slate-50 p-3.5 rounded-xl border border-slate-100">
                  <h4 className="font-bold text-slate-900 text-xs mb-1.5 flex items-center gap-2">
                    <span className="w-4 h-4 rounded-full bg-blue-600 text-white flex items-center justify-center text-[10px]">
                      {idx + 1}
                    </span>
                    {sec.q}
                  </h4>
                  <p className="text-slate-600 pl-6">{sec.a}</p>
                </div>
              ))}
            </div>
          )}

          {type === 'contact' && (
            <div className="space-y-3">
              {content.details.map((d, idx) => (
                <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-100">
                  <p className="text-[10px] uppercase font-bold text-slate-400 tracking-wider mb-0.5">
                    {d.label}
                  </p>
                  <p className="text-slate-900 font-medium text-xs">{d.value}</p>
                </div>
              ))}
            </div>
          )}

          {type === 'feedback' && (
            <div>
              {feedbackSubmitted ? (
                <div className="py-8 flex flex-col items-center text-center">
                  <div className="w-12 h-12 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mb-3">
                    <CheckCircle2 className="w-6 h-6" />
                  </div>
                  <h4 className="text-base font-bold text-slate-900">Thank You!</h4>
                  <p className="text-xs text-slate-500 mt-1 max-w-xs">
                    Your feedback has been logged into the TATVA platform operations backlog.
                  </p>
                </div>
              ) : (
                <form onSubmit={handleFeedbackSubmit} className="space-y-3">
                  <div>
                    <label className="block font-semibold text-slate-700 mb-1">Feedback Category</label>
                    <select
                      value={feedbackCategory}
                      onChange={(e) => setFeedbackCategory(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                    >
                      <option value="data_accuracy">Radar & Rainfall Data Accuracy</option>
                      <option value="ui_ux">Interface & Map Usability</option>
                      <option value="alerting">Disaster Alert Latency</option>
                      <option value="feature_request">Feature Request / Model Integration</option>
                    </select>
                  </div>
                  <div>
                    <label className="block font-semibold text-slate-700 mb-1">Email (Optional)</label>
                    <input
                      type="email"
                      value={feedbackEmail}
                      onChange={(e) => setFeedbackEmail(e.target.value)}
                      placeholder="scientist@imd.gov.in"
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-slate-700 mb-1">Your Observations / Feedback</label>
                    <textarea
                      required
                      rows={3}
                      value={feedbackMessage}
                      onChange={(e) => setFeedbackMessage(e.target.value)}
                      placeholder="Please detail your observation, anomaly report, or suggested improvement..."
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                    />
                  </div>
                  <div className="pt-2 flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={onClose}
                      className="px-4 py-2 rounded-xl text-slate-600 hover:bg-slate-100 font-semibold"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold inline-flex items-center gap-1.5 shadow-sm shadow-blue-600/30"
                    >
                      <Send className="w-3.5 h-3.5" />
                      Submit Feedback
                    </button>
                  </div>
                </form>
              )}
            </div>
          )}

          {(type === 'privacy' || type === 'terms' || type === 'accessibility') && (
            <div className="space-y-3">
              {content.text.map((p, idx) => (
                <p key={idx} className="bg-slate-50 p-3.5 rounded-xl border border-slate-100 text-slate-700 leading-relaxed">
                  {p}
                </p>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-slate-100 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
